services:
  db:
    image: mysql:latest
    container_name: department_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: department_management
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      - ./stored_procedures.sql:/docker-entrypoint-initdb.d/stored_procedures.sql
    networks:
      - department_network

  app:
    build: .
    container_name: department_app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=department_management
      - SERVER_PORT=8080
      - JWT_SECRET=your_jwt_secret
      - EMAIL_FROM=roxxana.roxx7@gmail.com
      - EMAIL_PASSWORD=Milka777!
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - department_network

volumes:
  db_data:

networks:
  department_network: